logging:

  level:

    org: ${log-framework:ERROR}

    ru:
      tchallenge: ${log:INFO}

server:

  error:
    whitelabel:
      enabled: 'false'

  port: ${port:5000}

spring:

  main:
    banner-mode: 'off'

  mvc:
    throw-exception-if-no-handler-found: 'true'

  resources:
    add-mappings: 'false'

tchallenge:

  client:

    internal:
      url: ${url:http://t-challenge.ru}
      service-kernel-url: ${service-kernel-url:http://data.t-challenge.ru}
